-- Criar tabela de endereços
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE enderecos CASCADE CONSTRAINTS';

EXCEPTION WHEN OTHERS THEN NULL;

END;

/

CREATE TABLE enderecos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado VARCHAR2 (25 CHAR) NOT NULL,
    cidade VARCHAR2 (35 CHAR) NOT NULL,
    bairro VARCHAR2 (40 CHAR) NOT NULL,
    rua VARCHAR2 (100 CHAR) NOT NULL,
    numero NUMBER NOT NULL,
    complemento VARCHAR2 (50 CHAR)
);
-- Inserir dados na tabela endereços
INSERT INTO
    enderecos (
        estado,
        cidade,
        bairro,
        rua,
        numero,
        complemento
    )
VALUES (
        'ES',
        'Vitória',
        'Jardim da Penha',
        'Rua Tupinambás',
        342,
        'Sala 404'
    );

INSERT INTO
    enderecos (
        estado,
        cidade,
        bairro,
        rua,
        numero,
        complemento
    )
VALUES (
        'ES',
        'Vitória',
        'Monte Belo',
        'Rua Anselmo Serrate',
        199,
        NULL
    );

INSERT INTO
    enderecos (
        estado,
        cidade,
        bairro,
        rua,
        numero,
        complemento
    )
VALUES (
        'ES',
        'Vitória',
        'Enseada do Suá',
        'Av. Nossa Sra. dos Navegantes',
        955,
        NULL
    );

-- Criar tabela de barbearias
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE barbearias CASCADE CONSTRAINTS';

EXCEPTION WHEN OTHERS THEN NULL;

END;

/

CREATE TABLE barbearias (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2 (155 CHAR) NOT NULL,
    telefone VARCHAR2 (17 CHAR) NOT NULL,
    id_endereco NUMBER NOT NULL,
    CONSTRAINT fk_endereco FOREIGN KEY (id_endereco) REFERENCES enderecos (id)
);
-- Inserir dados na tabela barbearias
INSERT INTO
    barbearias (nome, telefone, id_endereco)
VALUES (
        'Barbearia A',
        '(27) 99513-5998',
        1
    );

INSERT INTO
    barbearias (nome, telefone, id_endereco)
VALUES (
        'Barbearia B',
        '(27) 90909-7142',
        2
    );

INSERT INTO
    barbearias (nome, telefone, id_endereco)
VALUES (
        'Barbearia C',
        '(27) 99310-9941',
        3
    );

-- Criar tabela de barbeiros
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE barbeiros CASCADE CONSTRAINTS';

EXCEPTION WHEN OTHERS THEN NULL;

END;

/

CREATE TABLE barbeiros (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2 (155 CHAR) NOT NULL,
    senha VARCHAR2 (255 CHAR) NOT NULL,
    id_barbearia NUMBER NOT NULL,
    foto VARCHAR2 (255 CHAR) NOT NULL,
    admin NUMBER (1) NOT NULL CHECK (admin IN (0, 1)),
    CONSTRAINT fk_barbearia FOREIGN KEY (id_barbearia) REFERENCES barbearias (id)
);
-- Inserir dados na tabela barbeiros
INSERT INTO
    barbeiros (
        nome,
        senha,
        id_barbearia,
        foto,
        admin
    )
VALUES (
        'admin',
        '$2y$10$OXZA3S5qMCak3pKwwHVD2OL0oOFT2PQ4VOqOZ/QYf29eI5YvAtPJa',
        1,
        'imgs/default_image_barbeiro.png',
        1
    );

-- Criar tabela de tipos de cortes
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE tipos_cortes CASCADE CONSTRAINTS';

EXCEPTION WHEN OTHERS THEN NULL;

END;

/

CREATE TABLE tipos_cortes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2 (30 CHAR) NOT NULL
);
-- Inserir dados na tabela tipos de cortes
INSERT INTO tipos_cortes (nome) VALUES ('Pézinho');

INSERT INTO tipos_cortes (nome) VALUES ('Sobrancelha');

INSERT INTO tipos_cortes (nome) VALUES ('Corte com Máquina');

INSERT INTO tipos_cortes (nome) VALUES ('Disfarçado');

INSERT INTO tipos_cortes (nome) VALUES ('Barba');

INSERT INTO tipos_cortes (nome) VALUES ('Bigode');

INSERT INTO tipos_cortes (nome) VALUES ('Pintar');

INSERT INTO
    tipos_cortes (nome)
VALUES (
        'Completo (Barba, Cabelo e Bigode)'
    );

-- Criar tabela de cortes
BEGIN EXECUTE IMMEDIATE 'DROP TABLE cortes CASCADE CONSTRAINTS';

EXCEPTION WHEN OTHERS THEN NULL;

END;

/

CREATE TABLE cortes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_corte DATE NOT NULL,
    nome_cliente VARCHAR2 (155 CHAR) NOT NULL,
    telefone_cliente VARCHAR2 (17 CHAR) NOT NULL,
    id_barbeiro NUMBER NOT NULL,
    cliente VARCHAR2 (45 CHAR) NOT NULL,
    tipo_corte NUMBER,
    horario TIMESTAMP NOT NULL,
    CONSTRAINT fk_barbeiro FOREIGN KEY (id_barbeiro) REFERENCES barbeiros (id),
    CONSTRAINT fk_tipo_corte FOREIGN KEY (tipo_corte) REFERENCES tipos_cortes (id)
);
-- Inserir dados na tabela cortes (exemplo)
INSERT INTO
    cortes (
        data_corte,
        nome_cliente,
        telefone_cliente,
        id_barbeiro,
        cliente,
        tipo_corte,
        horario
    )
VALUES (
        TO_DATE ('2024-11-26', 'YYYY-MM-DD'),
        'Cliente Exemplo',
        '(27) 99999-9999',
        1,
        'Sim',
        1,
        TO_TIMESTAMP ('14:30', 'HH24:MI')
    );

-- Criar tabela de horários
BEGIN EXECUTE IMMEDIATE 'DROP TABLE horarios CASCADE CONSTRAINTS';

EXCEPTION WHEN OTHERS THEN NULL;

END;

/

CREATE TABLE horarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    horario TIMESTAMP NOT NULL
);
-- Inserir dados na tabela horários
INSERT INTO
    horarios (horario)
VALUES (
        TO_TIMESTAMP ('09:00', 'HH24:MI')
    );

INSERT INTO
    horarios (horario)
VALUES (
        TO_TIMESTAMP ('09:30', 'HH24:MI')
    );

INSERT INTO
    horarios (horario)
VALUES (
        TO_TIMESTAMP ('10:00', 'HH24:MI')
    );

INSERT INTO
    horarios (horario)
VALUES (
        TO_TIMESTAMP ('10:30', 'HH24:MI')
    );

INSERT INTO
    horarios (horario)
VALUES (
        TO_TIMESTAMP ('11:00', 'HH24:MI')
    );

INSERT INTO
    horarios (horario)
VALUES (
        TO_TIMESTAMP ('11:30', 'HH24:MI')
    );

INSERT INTO
    horarios (horario)
VALUES (
        TO_TIMESTAMP ('12:00', 'HH24:MI')
    );

INSERT INTO
    horarios (horario)
VALUES (
        TO_TIMESTAMP ('12:30', 'HH24:MI')
    );

INSERT INTO
    horarios (horario)
VALUES (
        TO_TIMESTAMP ('13:00', 'HH24:MI')
    );

INSERT INTO
    horarios (horario)
VALUES (
        TO_TIMESTAMP ('13:30', 'HH24:MI')
    );

INSERT INTO
    horarios (horario)
VALUES (
        TO_TIMESTAMP ('14:00', 'HH24:MI')
    );

INSERT INTO
    horarios (horario)
VALUES (
        TO_TIMESTAMP ('14:30', 'HH24:MI')
    );

INSERT INTO
    horarios (horario)
VALUES (
        TO_TIMESTAMP ('15:00', 'HH24:MI')
    );

INSERT INTO
    horarios (horario)
VALUES (
        TO_TIMESTAMP ('15:30', 'HH24:MI')
    );

INSERT INTO
    horarios (horario)
VALUES (
        TO_TIMESTAMP ('16:00', 'HH24:MI')
    );

INSERT INTO
    horarios (horario)
VALUES (
        TO_TIMESTAMP ('16:30', 'HH24:MI')
    );

INSERT INTO
    horarios (horario)
VALUES (
        TO_TIMESTAMP ('17:00', 'HH24:MI')
    );

INSERT INTO
    horarios (horario)
VALUES (
        TO_TIMESTAMP ('17:30', 'HH24:MI')
    );

INSERT INTO
    horarios (horario)
VALUES (
        TO_TIMESTAMP ('18:00', 'HH24:MI')
    );

INSERT INTO
    horarios (horario)
VALUES (
        TO_TIMESTAMP ('18:30', 'HH24:MI')
    );

INSERT INTO
    horarios (horario)
VALUES (
        TO_TIMESTAMP ('19:00', 'HH24:MI')
    );